spring.application.name=titan_gym_backend

# Server Configuration
# ===============================
server.port=8082

# ===============================
# PostgreSQL Database
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/gym_management_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Logging
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# ===============================
# Cloudinary Configuration
# ===============================

cloudinary.cloud-name=iisa7tek
cloudinary.api-key=585335959758954
cloudinary.api-secret=f_-HooCUUOLZQmTvZqDDme7amJs
