spring.application.name=titan_gym_backend

# Server Configuration
# ===============================
server.port=${PORT:8082}
server.address=0.0.0.0

# ===============================
# PostgreSQL Database
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# ===============================
# Logging
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# ===============================
# Cloudinary Configuration
# ===============================

cloudinary.cloud-name=iisa7tek
cloudinary.api-key=585335959758954
cloudinary.api-secret=f_-HooCUUOLZQmTvZqDDme7amJs
